# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 411caf353c53fc0321eeea9b66ab66edf5144cc94158f7f380d2bebdb161923667ba7adae9a0739e6b30a8bdf0347631c6cbe1042a6a57a75658e96c0ca1af5a
  stripe_public_key: pk_test_Ki4ldWqsSYphdzeFV9LFf1lN
  stripe_secret_key: sk_test_numj9o4XY4tDdFv8OJCcKy1w
  toggl_key: 89ab6a5f703bd339d682809496e8790c

test:
  secret_key_base: 5e1174ed2df910f388187c626ae95a15ae21da3580ad4fd8fa8d4f98fd1070cc45e9a8fc1db8ff7d8af5b69afb991eba2ef61b4bf3c13c9586d8227c97827d98
  stripe_public_key: pk_test_Ki4ldWqsSYphdzeFV9LFf1lN
  stripe_secret_key: sk_test_numj9o4XY4tDdFv8OJCcKy1w
  toggl_key: 89ab6a5f703bd339d682809496e8790c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  toggl_key: <%= ENV["TOGGL_KEY"] %>
